### PR TITLE
fix: Border Of The Error Fields

### LINKED ISSUE #17: The Border Of The Error Fields Is Too Thick
The color used in the borders of the text fields is very thick and of a different tone, it is necessary to include the alert icon that is in the design.
The size of the text used in the alerts is also very large, check the fonts.

Screenshot 2022-03-22 074615
image

#Reference 

https://www.figma.com/file/Pw5EfnvCLnXox2mFS40kdW/Azordev?node-id=0%3A1

_Originally posted by @angelik0828 in https://github.com/Azordev/search-by-time-github/issues/16#issuecomment-1075221584_

### PR DESCRIPTION
**Pull request by mdibuhossain**
fixes #17 

#### Screenshots
image

### CODE REVIEW

File: src/js/utils.js [hunk 1]
```diff
@@ -78,7 +78,7 @@ export const validateForm = () => {
     if (fielValid[idField].required && !value) {
       field.classList.add("error");
       spanError.classList.add("span_error");
-      spanError.innerHTML =
+      spanError.innerHTML = "<i class=\"fa fa-exclamation-triangle\">&nbsp&nbsp</i>" +
         "Please enter the required field";
```
Comment (e-azocar) [inline src/js/utils.js]: You could use this to avoid `\"fa fa-exclamation-triangle\"`
```suggestion
      spanError.innerHTML = `<i class="fa fa-exclamation-triangle">&nbsp&nbsp</i> Please enter the required field`;
```

**Review by e-azocar — APPROVED** [review]
It's ok, but I have one comment

**Review by Israel-Laguan — APPROVED** [review]

File: src/js/utils.js (hunk 1 above)
Comment (mdibuhossain) [reply src/js/utils.js]: Done. I updated it.

**Review by Israel-Laguan — APPROVED** [review]
